# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LLM_Tarim',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/LLM_Tarim',
                'lib_path': 'LLM_Tarim'},
  'syms': {'LLM_Tarim.core': {'LLM_Tarim.core.foo': ('core.html#foo', 'LLM_Tarim/core.py')}}}
